### ISSUE TITLE
Name ApiError is not defined !

### ISSUE THREAD

**Issue by ChauncyYinXun** [daniel-ball/broadcaster#1]
Hi, I am getting the following error after running your script: 

![image](https://user-images.githubusercontent.com/32704417/103355832-44ae2c00-4aea-11eb-92df-7700b689ca9b.png)

Are you missing some scripts?

**Comment by ChauncyYinXun** [comment]
@daniel-ball Would you have any idea where went wrong? Thanks!

**Comment by daniel-ball** [comment]
Did you sign up for a webexteams account at developer.webex.com and get your access token?

**Comment by daniel-ball** [comment]
Line 33 is pulling your avatar image from Webex. If nothing else works, try uploading an avatar.

**Comment by ChauncyYinXun** [comment]
It's all good! Thank you @daniel-ball

**Comment by daniel-ball** [comment]
My pleasure!
